const SUPABASE_URL = "https://aehqeddpepmklxktlclq.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlaHFlZGRwZXBta2x4a3RsY2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgxMTEwNjgsImV4cCI6MjA5MzY4NzA2OH0.xg0loxoFziciF6dJgo5xzFRU2gD7Uv-rbuJSLnFyJU4";

export const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);